version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=archcore
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"