version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=archcore

  api:
    build:
      context: .
      dockerfile: src/apps/Charity.Api/Dockerfile
    ports:
      - "5005:80"
    environment:
      - "ConnectionStrings__ApplicationDbContext=User ID=postgres;Password=archcore;Server=postgres;Port=5432;Database=charity;Integrated Security=true;Pooling=true;"
    restart: on-failure
    depends_on:
      - postgres